
version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@2.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
        # node-version: "16.14"
      - node/install-packages: 
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run cy:run
      - run : 
          name : Run build
          command: npm run build 
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build:
    jobs:
      # - build
      - cypress/run